module HttpStatusCodes
  HTTP_SUCCESS = 200
  HTTP_BAD_REQUEST_CODE = 400
  HTTP_UNAUTHORIZED_CODE = 401
  HTTP_FORBIDDEN_CODE = 403
  HTTP_NOT_FOUND_CODE = 404
  HTTP_INVALID_PARAMS = 422
  HTTP_UNPROCESSABLE_ENTITY_CODE = 429
  HTTP_SERVICE_OFFLINE = 503
end
