language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: OngJ8mKWSp/xdFyhx90QX1KSRzFPoI0aXZw4c4e4SoVQX+og9T/UvcIa020rboIthu9XkAXzxSbSYBuwLw0zDxQiod87PsaD5ViEWtaLqWbz9Ctp2LkBOIYXTDA52lilDVTHFBp3foZiYzRnf+cKtq5g1MDDe7o/DTwy4GRTnlCPThXlRKxd287zdzChv2J2ZbD5Ds/tquwHwXvryQi1TZsgmWUdSyOJknz+DcJEMU0WpLs5VKXt89kyEEUAIb3pG6Y9fET6ZQGpwbYphNRH5lwdCmSIazgkaYsRPPTwPj1y8TOcYrMhAzhV9YK3yINoRFn2gYoC3Ybyo/5v46kfuPn+y2csy6N0ByYWiR3P2vwaLmC4TzdgVZq18tuoQgoL5HklNWRbHlwxafm+c0PSZX+TfHExRfVM6Z/vE0mD86mbQYdtZjZzbGaA1QooX692saqEE+eczfSsLRFVugwAIg+T9Eoat6eWs41JB/+LS3bsnyXzk5sldIChTP2iz795n13AW7ajMwB9A0Ga01N4yp1Ro6/CwMHgYjXHkEGL5DSKEjNeZOiJIy/aL36FRo/jXA2O71P8WPOmL6ypTdhtsC/jEHsKr30igcXsJ5h8nfrNWkUbndmFSCuYxjv5sgIavI29avZAizmWKw9ZTIIMqiVQm2BsiAeJT/Z2odTLv2I=
  app: viewing_party
  run: rails db:migrate
